import sys, time, json
sys.path.insert(0, '/home/claude/sf19coach/tests/e2e')
from helpers import *
from playwright.sync_api import sync_playwright

URL = 'http://localhost:8080/'
logs = []
def legal(page):
    fen = page.evaluate("(() => { const s = __sf19.playState.value; return s.tree.lineEnd(s.tree.root).fen })()")
    return fen, page.evaluate("fen => __sf19.legal(fen)", fen)

with sync_playwright() as p:
    b, ctx = new_browser(p)
    page = ctx.new_page()
    attach_logs(page, logs)
    page.add_init_script("if (!localStorage.getItem('sf19c.settings.v1')) localStorage.setItem('sf19c.settings.v1', JSON.stringify({welcomed: true, variant: 'lite'}))")
    page.goto(URL)
    page.wait_for_function("window.__sf19 && window.__sf19.engineManager.state.value.status === 'ready'", timeout=60000)
    # --- game as black with a clock, normal mode
    page.evaluate("__sf19.play.start({color: 'black', elo: 1800, max: false, clock: true, base: 3, inc: 2, movetime: 1000, mode: 'normal'})")
    st = wait_phase(page, 'user', 30)
    print('engine opened:', st['moves'])
    time.sleep(1.2)
    clk = page.evaluate("JSON.stringify(__sf19.play.s.config.clock)")
    fen, moves = legal(page)
    mv = 'e7e5' if 'e7e5' in moves else moves[0]
    click_move(page, mv)
    # premove while engine thinks: try g8f6 (usually legal)
    time.sleep(0.05)
    drag_move(page, 'g8f6')
    st = wait_phase(page, 'user', 30)
    time.sleep(1.0)
    st = play_state(page)
    print('after premove:', st['moves'], st['phase'])
    page.screenshot(path='/tmp/shots/40-black-clock.png')
    clocks = page.evaluate("JSON.stringify({w: __sf19.play.clockOf('white'), b: __sf19.play.clockOf('black')})")
    print('clocks:', clocks)
    # reload -> restore
    page.reload()
    page.wait_for_function("window.__sf19 && window.__sf19.engineManager.state.value.status === 'ready'", timeout=60000)
    time.sleep(1)
    st = play_state(page)
    print('restored:', st['status'], st['moves'], st['phase'])
    page.screenshot(path='/tmp/shots/41-restored.png')
    # --- promotion test (training)
    page.evaluate("__sf19.play.start({color: 'white', elo: 1500, max: false, clock: false, movetime: 500, mode: 'training', coach: true, pause: false, evalbar: true, hints: true, takebacks: true, alertOpp: true, startFen: '8/4P3/8/8/8/k7/8/K7 w - - 0 1'})")
    wait_phase(page, 'user', 20)
    click_move(page, 'e7e8')
    time.sleep(0.5)
    page.screenshot(path='/tmp/shots/42-promo.png')
    print('promo dialog:', page.locator('.promo-choice').count())
    page.locator('.promo-choice').nth(1).click()  # knight (queen, knight, rook, bishop)
    time.sleep(0.5)
    st = play_state(page)
    print('after promo:', st['moves'], st['status'], st['result'])
    page.evaluate("__sf19.play.start({color: 'white', elo: 1500, max: false, clock: false, movetime: 500, mode: 'training', coach: true, pause: false, evalbar: true, hints: true, takebacks: true, alertOpp: true, startFen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4'})")
    wait_phase(page, 'user', 20)
    click_move(page, 'b1c3')
    st = wait_phase(page, 'user', 40)
    print('moves:', st['moves'])
    # threat
    page.keyboard.press('t')
    time.sleep(2.5)
    print('threat:', page.evaluate("JSON.stringify(__sf19.playState.value.threat)"))
    page.screenshot(path='/tmp/shots/43-threat.png')
    # --- mobile screenshots
    mctx = b.new_context(viewport={'width': 390, 'height': 844}, is_mobile=True, has_touch=True, device_scale_factor=2)
    m = mctx.new_page()
    attach_logs(m, logs)
    m.add_init_script("localStorage.setItem('sf19c.settings.v1', JSON.stringify({welcomed: true, variant: 'lite'}))")
    m.goto(URL)
    m.wait_for_function("window.__sf19 && window.__sf19.engineManager.state.value.status === 'ready'", timeout=60000)
    m.screenshot(path='/tmp/shots/50-mobile-welcome.png')
    m.evaluate("__sf19.play.start({color: 'white', elo: 2000, max: false, clock: true, base: 10, inc: 5, movetime: 800, mode: 'training', coach: true, pause: true, evalbar: true, hints: true, takebacks: true, alertOpp: true})")
    wait_phase(m, 'user', 20)
    fen, moves = legal(m)
    x, y = square_center(m, 'e2'); m.touchscreen.tap(x, y); time.sleep(0.1)
    x, y = square_center(m, 'e4'); m.touchscreen.tap(x, y); time.sleep(0.2)
    wait_phase(m, 'user', 40)
    time.sleep(1.5)
    m.screenshot(path='/tmp/shots/51-mobile-play.png', full_page=True)
    m.evaluate("__sf19.setMode('analysis')")
    time.sleep(2)
    m.screenshot(path='/tmp/shots/52-mobile-analysis.png', full_page=True)
    m.evaluate("__sf19.setMode('library')")
    time.sleep(1)
    m.screenshot(path='/tmp/shots/53-mobile-library.png', full_page=True)
    b.close()
print('\n'.join(logs[-30:]))
