import sys, time, json
sys.path.insert(0, '/home/claude/sf19coach/tests/e2e')
from helpers import *
from playwright.sync_api import sync_playwright
PGN = open('/home/claude/sf19coach/tests/e2e/sample.pgn').read()
with sync_playwright() as p:
    b, ctx = new_browser(p)
    page = ctx.new_page()
    logs = []; attach_logs(page, logs)
    page.add_init_script("localStorage.setItem('sf19c.settings.v1', JSON.stringify({welcomed: true, variant: 'lite', playerName: 'Konstantinos', reviewPreset: 'fast'}))")
    page.goto('http://localhost:8080/')
    page.wait_for_function("window.__sf19 && window.__sf19.engineManager.state.value.status === 'ready'", timeout=60000)
    time.sleep(0.5)
    page.screenshot(path='/tmp/shots/60-welcome.png')
    page.locator('.tab').nth(1).click(); time.sleep(0.3)
    page.locator('.action-btns button[title="Εισαγωγή PGN/FEN"]').click()
    page.locator('.modal textarea').fill(PGN)
    page.locator('.modal .modal-foot .btn-primary').click()
    page.wait_for_function("__sf19.anState.value.review.status === 'done'", timeout=400000)
    time.sleep(0.5)
    page.locator('.review-actions button[title="Επόμενο λάθος"]').click(); time.sleep(1.5)
    page.screenshot(path='/tmp/shots/61-verdict.png')
    page.locator('.verdict-bar').click(); time.sleep(0.5)
    page.screenshot(path='/tmp/shots/62-verdict-open.png')
    print(json.dumps(page.evaluate("(() => { const s = __sf19.anState.value.review.summary; return { w: s.white.accuracy, b: s.black.accuracy, wc: s.white.counts, bc: s.black.counts } })()")))
    b.close()
    print('\n'.join(logs[-10:]))
